first_task_done
Go0osee/FlightsApp pull request #1
Opened 2022-03-30 16:22 UTC by Go0osee

2022-03-30 21:11 UTC, Vlad94051 requested changes

2022-03-30 21:11 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/domain/ViewModelModule.kt
> +        MainViewModel(get())
На каждый экран должна быть своя вью модель, а не одна на все

2022-03-30 21:11 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/HistoryFragment.kt
> +        viewModel.getFlights()
лушче не гет а load, get подразумевает что этот метод имеет тип возвращаемого значения : List<Flight>

2022-03-30 21:11 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/InputFragment.kt
> +    }
валидация должна быть во вью модели

2022-03-30 21:11 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/InputFragment.kt
> +            }
то жееее вью модель

2022-03-30 21:11 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/InputFragment.kt
> +                "Взрослый"
в ресурсыы

2022-03-30 21:11 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/InputFragment.kt
> +                "Взрослый"
а вообще в enum говорил завернуть

2022-03-30 21:11 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/ext/Ext.kt
> +        .show()
не место такому в экстеншнах, заводи отдельный класс типо date/time manager и там это все делай

2022-03-30 21:11 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/ext/Ext.kt
> +var dateAndTime = Calendar.getInstance()
что это тут делает тож не понятно

2022-03-30 21:11 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/recycler/FlightViewHolder.kt
> +        itemView.age.text = item.age
ну тут with(itemView) так и напрашивается

2022-03-30 21:11 UTC, Vlad94051 commented on app/src/main/res/layout/fragment_input.xml
все dp в dimens

2022-03-30 21:11 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/MainViewModel.kt
> +    fun getFlights() {
можно было бы вызывать в ините (ниже коммент об один экран -  одна вью модель)

2022-03-30 21:11 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/MainViewModel.kt
> +                age
что не передавать такую кучу параметров, можно тут объектик какой нить создать типо FlightPresentation, и в домене уже мапить (да получится 3 модельки)

2022-04-01 10:44 UTC, Vlad94051 requested changes

2022-04-01 10:44 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/data/mapper/MapperExt.kt
> +        arrivalTime = arrivalTime.toDateString("dd.MM.yyyy") + ", " + arrivalTime.toTimeString("HH:mm:ss"),
кажется что это можно сделать через simple date format

2022-04-01 10:44 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/data/mapper/MapperExt.kt
> +        arrivalTime = arrivalTime.toDateString("dd.MM.yyyy") + ", " + arrivalTime.toTimeString("HH:mm:ss"),
ну и ниже тоже

2022-04-01 10:44 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/data/storage/entity/FlightEntity.kt
> +    val age: AgeEnum,
слово Enum в названии Enum-a писать не надо, ты же не пишешь FlightEntityClass

2022-04-01 10:44 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/domain/interactor/FlightInteractor.kt
> +    )
в одну строку вроде влазит

2022-04-01 10:44 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/domain/models/AgeEnum.kt
> +    CHILD("Детский")
в ресурсы строки

2022-04-01 10:44 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/ext/Ext.kt
> +        setNegativeButton("Отмена", null)
в strings

2022-04-01 10:44 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/ext/Ext.kt
> +    {
скобка в странном месте

2022-04-01 10:44 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/fragment/InputFragment.kt
> +                },
почему не передать во вью модель isChecked и там проверять детский или взрослый?

2022-04-01 10:44 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/recycler/FlightViewHolder.kt
> +            arrivalTime.text = item.arrivalTime.toTimeString("HH:mm:ss") + ",\n" + item.arrivalTime.toDateString("dd.MM.yyyy")
тож через simple date format можно. во вью холдер данные должны приходить уже готовыми для отображение, то есть это преобразование надо делать в мапперах или вью модели/интеракторе но не тут

2022-04-01 10:44 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/viewmodel/HistoryViewModel.kt
> +            }.join()
там вроде есть doOnComplete метод или что-то такое

2022-04-01 10:44 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/viewmodel/InputViewModel.kt
> +    }
почему бы не сделать его private и не вызывать его в init у вью модели

2022-04-01 10:44 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/viewmodel/InputViewModel.kt
> +            showSnack(view.context.getString(R.string.error), view)
открытие снека должно вызываться внутри фрагмента, тут ты можешь только отправить событие во фрагмент мол валидация не пройдена

2022-04-01 10:44 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/dataTimePicker/DataTimePicker.kt
> +class DataTimePicker {
пикеры попозже гляну

2022-04-01 15:35 UTC, Go0osee commented on app/src/main/java/com/example/flightsapp/presentation/viewmodel/HistoryViewModel.kt
> +            }.join()
не нашел

2022-04-03 08:43 UTC, Vlad94051 requested changes
ставлю 4 из 5 этой домашке

2022-04-03 08:43 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/data/mapper/MapperExt.kt
> +        arrivalTime = arrivalTime.toDate("dd.MM.yyyy, HH:mm:ss"),
форматы лучше тут рядом в константы вынести

2022-04-03 08:43 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/data/storage/entity/FlightEntity.kt
> +    val departureCity: String,
@ColumnName не мешало бы проставить (везде)

2022-04-03 08:43 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/domain/models/AgeType.kt
> +enum class AgeType(val age: Int) {
переименуй название параметра на ageTypeId, и поставь перед ним аннотацию @StringRes, это обязывает передавать сюда только id строкового ресурса

2022-04-03 08:43 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/activity/MainActivity.kt
> +
пустая строка лишняя

2022-04-03 08:43 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/clicklistener/DeleteClickListener.kt
> +interface DeleteClickListener {
Я вроде говорил уже, что листенер всегда лучше называть типо OnOrderItemClickListener, а внутри него делать метод а-ля onDeleteClickListener, чтоб если придется ловить клик на другую вьюшку в элементе название этого интерфейса подходило. например: 
```
interface DeleteClickListener {
        fun deleteClickListener(flight: Flight)
        fun saveClickListener(flight: Flight) // если появится кнопка сохранения
        fun likeClickListener(flight: Flight). // если появится кнопка лайка
```

2022-04-03 08:43 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/viewmodel/HistoryViewModel.kt
> +            }.join()
invokeOnCompletion называется метод, сори перепутал

2022-04-03 08:43 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/viewmodel/InputViewModel.kt
> +                    },
можно в метод отдельный вынести прямо в enum'e

2022-04-03 08:43 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/ext/Ext.kt
> +}
этого пацыка существовать не должно

2022-04-03 08:43 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/ext/Ext.kt
> +    return !Regex("""\w{2}\d{7}""").matches(this)
а почему ты возвращаешь "не regex", можно назвать метод isPassportNumberValid и возвращать без не 
(вообще если есть возможность писать без не лучше писать без не)

2022-04-03 08:43 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/ext/Ext.kt
> +    return !Regex("""\w{2}\d{7}""").matches(this)
ну и сам паттерн лучше в константу над методом вынести

2022-04-03 08:43 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/ext/Ext.kt
> +fun Fragment.showAlertDialog(action: () -> Unit) {
сейчас ситуация какая - у тебя во всех фрагментах есть метод showAlertDialog, но не любой алерт (нельзя передать тайтл, негатив батон, текстовки различные итд) нужно назвать метод showDeleteOrderAlertMessage (и лучше сделать его экстеншном к HistoryFragment кажется)

2022-04-03 08:43 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/ext/Ext.kt
> +fun Fragment.showAlertDialog(action: () -> Unit) {
а так за метод 🥇

2022-04-03 08:43 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/fragment/InputFragment.kt
> +                switchAge.isChecked,
👍

2022-04-03 08:43 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/viewmodel/InputViewModel.kt
> +                    arrivalTime = ("$arrivalDate, $arrivalTime").toDate("dd.MM.yyyy, HH:mm:ss"),
форматы тож в константы (можно завести даже отдельный object Formats, тк ты форматы по всему проекту юзаешь, и закинуть в константы внутри этого объекта)

2022-04-03 08:43 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/utils/MapperExt.kt
> +    SimpleDateFormat("HH:mm:ss,\ndd.MM.yyyy").format(this)
тож константы

2022-04-03 08:43 UTC, Vlad94051 commented on app/src/main/res/layout/fragment_input.xml
> +    <TextView
А почему ты тред заресолвил, ты не все dp в dimens вынес?

2022-04-03 08:43 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/dataTimePicker/DataTimePicker.kt
> +    var dateAndTime = Calendar.getInstance()
вроде стоит приватным сделать

2022-04-03 08:43 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/dataTimePicker/DataTimePicker.kt
> +    fun setDate(textView: TextView, context: Context) {
контекст можно в конструктор, а не в методы передавать

2022-04-03 08:43 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/dataTimePicker/DataTimePicker.kt
> +            .show()
```suggestion
        ).show()
```

2022-04-03 08:43 UTC, Vlad94051 commented on app/src/main/java/com/example/flightsapp/presentation/dataTimePicker/DataTimePicker.kt
> +    }
ну а так остальное норм

2022-04-07 10:38 UTC, Vinny94051 commented on app/src/main/java/com/example/flightsapp/presentation/fragment/HistoryFragment.kt
> +        }
вот этот кусочек лучше то же сделать по событию. То есть тут ты вызываешь метод viewModel.onItemSwiped() и там уже разруливаешь, что тебе нужно во фрагменте, а что можно оставить во фрагменте. Потому что доставать данные из лайв даты как тут сделал

```
 historyViewModel.flights.value?.get(viewHolder.adapterPosition)
                            ?.let { historyViewModel.deleteFlight(it) }
```
это не хорошо (именно обращение к value не во viewModel)

2022-04-09 20:35 UTC, Vinny94051 commented on app/src/main/java/com/example/flightsapp/presentation/fragment/HistoryFragment.kt
> +        binding.recycler.layoutManager = LinearLayoutManager(requireContext())
```
binding.recycler.apply {
  // your code
}
```

2022-04-13 13:16 UTC, merged